# Generated by Django 2.1.5 on 2022-06-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200906_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
    ]
