# Generated by Django 2.1.5 on 2022-07-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20220630_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='customizable',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='glutten_free',
        ),
    ]
